import { createDateSchema } from './date-schema'
import type { GuiaSadtFieldDefinition } from './types'

export const dataExecucaoField: GuiaSadtFieldDefinition = {
	name: 'dataExecucao',
	label: '36. Data',
	placeholder: 'DDMMAAAA',
	maxLength: 8,
	rows: 5,
	lineMaxLength: 8,
	schema: createDateSchema('A Data de Execução', true),
	overlayFields: [
		{
			id: 'dataExecucao-1',
			x: 53,
			y: 663,
			width: 190,
			height: 21,
			length: 8,
			gap: 0,
			fontSize: 14,
			fontWeight: 500,
			align: 'center',
			type: 'number',
		},
		{
			id: 'dataExecucao-2',
			x: 53,
			y: 684,
			width: 190,
			height: 21,
			length: 8,
			gap: 0,
			fontSize: 14,
			fontWeight: 500,
			align: 'center',
			type: 'number',
		},
		{
			id: 'dataExecucao-3',
			x: 53,
			y: 705,
			width: 190,
			height: 21,
			length: 8,
			gap: 0,
			fontSize: 14,
			fontWeight: 500,
			align: 'center',
			type: 'number',
		},
		{
			id: 'dataExecucao-4',
			x: 53,
			y: 726,
			width: 190,
			height: 21,
			length: 8,
			gap: 0,
			fontSize: 14,
			fontWeight: 500,
			align: 'center',
			type: 'number',
		},
		{
			id: 'dataExecucao-5',
			x: 53,
			y: 747,
			width: 190,
			height: 21,
			length: 8,
			gap: 0,
			fontSize: 14,
			fontWeight: 500,
			align: 'center',
			type: 'number',
		},
	],
	getOverlayValue: (overlayId, value) => {
		const index = Number(overlayId.split('-').pop()) - 1
		return value.split('|')[index] ?? ''
	},
}
